promtail:
  enabled: true
  serviceAccount:
    create: true
  config:
    lokiAddress: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: kubernetes-pods-name
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: ['__meta_kubernetes_namespace']
            action: keep
            regex: default
          - source_labels: ['__meta_kubernetes_pod_label_app']
            target_label: 'app'
          - source_labels: ['__meta_kubernetes_pod_name']
            target_label: 'pod'
          - source_labels: ['__meta_kubernetes_namespace']
            target_label: 'namespace'
