apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-service
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort   # easiest for single-node lab; k3s also has Traefik Ingress if you prefer
